# Generated by Django 6.1.1 on 2026-09-22 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunas', to='gestion_inmuebles.region')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('m2_construidos', models.FloatField()),
                ('m2_totales', models.FloatField()),
                ('estacionamientos', models.PositiveIntegerField(default=0)),
                ('habitaciones', models.PositiveIntegerField(default=0)),
                ('banos', models.PositiveIntegerField(default=0)),
                ('direccion', models.CharField(max_length=200)),
                ('precio_mensual', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('arrendado', 'Arrendado')], default='disponible', max_length=20)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmuebles', to='gestion_inmuebles.comuna')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL)),
                ('tipo_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_inmuebles.tipoinmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_inmuebles.tipousuario')),
            ],
        ),
    ]
